<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<footer>
        <div class="contenido-footer">
            <div class="seccion-footer">
                <h3>FashionStyle</h3>
                <p>Tu tienda de ropa en línea para toda la familia.</p>
            </div>
            <div class="seccion-footer">
                <h3>Enlaces</h3>
                <ul>
                    <li><a href="#inicio">Inicio</a></li>
                    <li><a href="#hombres">Hombres</a></li>
                    <li><a href="#mujeres">Mujeres</a></li>
                    <li><a href="#niños">Niños</a></li>
                    <li><a href="#contacto">Contacto</a></li>
                </ul>
            </div>
            <div class="seccion-footer">
                <h3>Redes Sociales</h3>
                <ul>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">Twitter</a></li>
                </ul>
            </div>
        </div>
    </footer>
    
</body>
</html>